easy = ["print 'hello world' in ascii style.",
"develop a calculator.",
"make a random number generator.",
"build password generator.",
"build a 'hello world' website.",
"make an email sender.",
"make name generator.",
"build password saver.",
"make to-do app.",
"build reminder app.",
"make alarm clock.",
"make world clock.",
"make countdown timer.",
"build an app for shot photos.",
"make an app that sends good morning messages.",
"build a note app.",
"make dice app.",
"make app for auto zipping your files.",
"develop weight conversion app.",
"make rock-paper-scissors game.",
"develop pomodoro timer."]

easy_number = len(easy) - 1



medium = ["build a blog website for you.",
"make your own text editor.",
"make a web scraper.",
"build a weather station.",
"make daily news app with web scraping.",
"develop a social media bot for publish something.",
"create a chat bot.",
"make an algorithm for track prices in online stores.",
"build an algorithm for find music to you.",
"make app that calculates your typing speed.",
"develop algorithm for finds musics into your mood.",
"make an app for shots timelapse videos.",
"build an day planner app.",
"create an app that makes you to jokes.",
"make app that add texts to photos.",
"build an app for add musics to videos.",
"make algorithm for detect languages.",
"develop an app for get texts from photos.",
"build basic piano.",
"redesign a website.",
"make app for organize your files.",
"build a music player.",
"develop text to speech app.",
"make an algorithm that send emails to you when earthquake happens.",
"build voice assistant.",
"make algorithm for finds movie to watch.",
"build tic-tac-toe game.",
"build your own portfolio website.",
"develop a weather app.",
"build an app that finds job advertisements into your skills and sends to you.",
"build a bot that likes your post on social media.",
"make your own url shortener app.",
"develop app that add bass to musics."]

medium_number = len(medium) - 1



hard = ["make a basic math problems solver.",
"create a AI that create articles for you.",
"make a complate 3D online game.",
"build a cloud server for storage your files.",
"develop an AI that organizes your photos according to their similarity.",
"create an AI that create articles for you.",
"develop an AI for create simple musics for you.",
"create an AI for simplify articles.",
"build an AI for find ideas for you.",
"make algorithm that takes vocals from musics.",
"create AI that detect and classify objects from photos and videos.",
"make AI face recognition app.",
"build virtual meeting platform.",
"build private messaging app.",
"create AI slogan generator.",
"develop an AI that writes music lyrics.",
"make auto subtitle generator for videos.",
"create AI that tries generate music names.",
"build an algorithm that simplifies your emails.",
"make face recognition home security system.",
"develop your own programming IDE.",
"make an app that saves articles you liked.",
"build auto image blocker that cencors inappropriate images in the websites.",
"build file upload website.",
"make an app that finds podcasts into your interests.",
"develop AI that generates good song names.",
"create an AI that generates meaningfull proverbs."]

hard_number = len(hard) - 1



impossible = ["build a complete search engine.",
"create an AI for create non human photos.",
"build an app for test the accuracy of the news.",
"make an AI for make rap beats.",
"create an AI automatic video editor.",
"make app for solve complicated math problems.",
"create autonomus car software.",
"make your own operation system.",
"build an algorithm for edit your videos.",
"develop an algorithm for mining cryptocurrencies and donates them to charities.",
"make AI for create fake humans.",
"develop an antivirus.",
"create AI systems talking to each other with their unique language.",
"make AI that tries find bugs in systems.",
"create algorithm that analyzes coffee and finds best coffee recipe.",
"develop an AI influencer that post something in social media.",
"create AI that calls somebody and talk them.",
"create an AI that writes meaningful poems.",
"develop an AI that plays chess like grandmaster.",
"make an AI that finds new food recepies.",
"make autonomus plane for simulation games.",
"develop an app that converts your website designs to actual website."]

impossible_number = len(impossible) - 1